enum USER_STATUS {
  INACTIVE = 1,
  ACTIVE = 2,
  BLOCK = 3,
  DELETED = 4,
}

enum USER_STATUS_CODE {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}

export { USER_STATUS, USER_STATUS_CODE };
